<?php

declare(strict_types=1);

namespace App\Lib\Dns;

use Illuminate\Support\Collection;
use RuntimeException;

class LocalDnsProvider implements DnsProviderInterface
{
    public function __construct(
        private readonly string $zonesPath,
        private readonly string $corefilePath,
        private readonly string $containerName,
        private readonly int $defaultTtl = 300,
    ) {
    }

    public function listRecords(): array
    {
        return [];
    }

    public function createRecord(array $params): array
    {
        return $params;
    }

    public function updateRecord(string $recordId, array $params): array
    {
        return $params;
    }

    public function deleteRecord(string $recordId): void
    {
    }

    public function regenerateZoneFile(string $domain, Collection $records): string
    {
        $domain = $this->normalizeDomain($domain);
        $serial = $this->nextSerial($domain);
        $zoneFilePath = $this->zoneFilePath($domain);

        $lines = [
            '$TTL ' . $this->defaultTtl,
            '@ IN SOA ns1.' . $domain . '. hostmaster.' . $domain . '. (',
            '  ' . $serial . ' ; serial',
            '  3600 ; refresh',
            '  900 ; retry',
            '  1209600 ; expire',
            '  300 ; minimum',
            ')',
            '@ IN NS ns1.' . $domain . '.',
            '',
        ];

        foreach ($records as $record) {
            $name = (string) ($record['name'] ?? '@');
            $type = (string) ($record['type'] ?? 'A');
            $content = (string) ($record['content'] ?? '');
            $ttl = (int) ($record['ttl'] ?? $this->defaultTtl);
            $priority = $record['priority'] ?? null;

            $normalizedName = $name === '' || $name === '@' ? '@' : $name;

            if ($type === 'MX' && $priority !== null) {
                $lines[] = sprintf('%s %d IN %s %d %s', $normalizedName, $ttl, $type, (int) $priority, $content);
            } else {
                $lines[] = sprintf('%s %d IN %s %s', $normalizedName, $ttl, $type, $content);
            }
        }

        $this->ensureDirectory($this->zonesPath);

        $written = file_put_contents($zoneFilePath, implode(PHP_EOL, $lines) . PHP_EOL);

        if ($written === false) {
            throw new RuntimeException('Failed to write zone file: ' . $zoneFilePath);
        }

        return $zoneFilePath;
    }

    public function regenerateCorefile(Collection $localZones): void
    {
        $lines = [
            '# Generated by LocalDnsProvider',
            '',
        ];

        foreach ($localZones as $zoneName) {
            $domain = $this->normalizeDomain((string) $zoneName);
            $lines[] = $domain . ':53 {';
            $lines[] = '    file ' . $this->zoneFilePath($domain);
            $lines[] = '    log';
            $lines[] = '    errors';
            $lines[] = '}';
            $lines[] = '';
        }

        $lines[] = '.:53 {';
        $lines[] = '    forward . 8.8.8.8 8.8.4.4';
        $lines[] = '    cache 300';
        $lines[] = '    log';
        $lines[] = '    errors';
        $lines[] = '}';

        $this->ensureDirectory(dirname($this->corefilePath));
        $written = file_put_contents($this->corefilePath, implode(PHP_EOL, $lines) . PHP_EOL);

        if ($written === false) {
            throw new RuntimeException('Failed to write Corefile: ' . $this->corefilePath);
        }
    }

    public function reloadCoreDns(): void
    {
        $command = sprintf('docker compose kill -s SIGHUP %s 2>/dev/null', escapeshellarg($this->containerName));
        exec($command, $output, $exitCode);

        if ($exitCode !== 0) {
            throw new RuntimeException('Failed to reload CoreDNS container: ' . $this->containerName);
        }
    }

    private function normalizeDomain(string $domain): string
    {
        return mb_strtolower(mb_rtrim(mb_trim($domain), '.'));
    }

    private function zoneFilePath(string $domain): string
    {
        return mb_rtrim($this->zonesPath, '/') . '/db.' . $domain;
    }

    private function nextSerial(string $domain): string
    {
        $todayPrefix = date('Ymd');
        $zoneFilePath = $this->zoneFilePath($domain);

        if (!is_file($zoneFilePath)) {
            return $todayPrefix . '01';
        }

        $content = file_get_contents($zoneFilePath) ?: '';

        if (preg_match('/\b(\d{10})\b\s*;\s*serial/', $content, $matches) !== 1) {
            return $todayPrefix . '01';
        }

        $current = $matches[1];

        if (str_starts_with($current, $todayPrefix)) {
            return (string) ((int) $current + 1);
        }

        return $todayPrefix . '01';
    }

    private function ensureDirectory(string $path): void
    {
        if (is_dir($path)) {
            return;
        }

        if (!mkdir($path, 0775, true) && !is_dir($path)) {
            throw new RuntimeException('Failed to create directory: ' . $path);
        }
    }
}
